import { DocumentMetadata } from '../models/Document';
import { db } from '../../lib/firebase';
import { collection, getDocs } from 'firebase/firestore';
import { AnonymizerService } from './AnonymizerService';
import { searchSimilarDocuments } from '../../data/repositories/DocumentRepository';
import { getFunctions, httpsCallable } from 'firebase/functions';
import app from '../../lib/firebase';

export class KnowledgeRetrievalService {
  async queryKnowledgeBase(query: string, userRole: string): Promise<string> {
    const scrubbedQuery = AnonymizerService.scrub(query);

    // 1. Fetch all documents from Firestore
    const snapshot = await getDocs(collection(db, 'documents'));
    const allDocs = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() } as DocumentMetadata));
    
    // 2. RBAC Filter: Only retrieve documents the user is allowed to see
    const accessibleDocs = allDocs.filter(doc => 
      doc.allowedRoles.includes('all') || doc.allowedRoles.includes(userRole.toLowerCase())
    );

    if (accessibleDocs.length === 0) {
      return "I could not find any documents in the knowledge base that you have permission to access to answer this query.";
    }

    // 3. Semantic vector search on chunks (gets top 3-5 similar chunks)
    const topChunks = await searchSimilarDocuments(scrubbedQuery, accessibleDocs, 3);

    if (topChunks.length === 0) {
      return `I searched your accessible documents but could not find any information relating to "${scrubbedQuery}".`;
    }

    // 4. Synthesize prompt using only the text of the top similar chunks
    const context = topChunks.map((chunk: any) => `Document: ${chunk.documentName || chunk.name}\nContent:\n${chunk.text || chunk.textContent}`).join("\n\n");

    const prompt = `You are an AI assistant for Breakthrough Management OS. Answer the query based on the following relevant document chunks.
Always explicitly cite the document name when using information from the provided chunks.

Relevant Chunks:
${context}

Query: ${scrubbedQuery}

Response:`;

    // 5. Call Gemini AI service via Firebase Cloud Function
    try {
      const functions = getFunctions(app);
      const generateGeminiContent = httpsCallable(functions, "generateGeminiContent");
      const resp = await generateGeminiContent({ prompt });
      return (resp.data as any).text || "No response generated by AI service.";
    } catch (error) {
      console.error("Failed to query Gemini in queryKnowledgeBase", error);
      return `Sorry, I encountered an error connecting to Gemini: ${(error as any).message || error}`;
    }
  }
}

export const knowledgeRetrieval = new KnowledgeRetrievalService();
